services:
  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: city-game-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: city_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js application
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: city-game-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: city_game
      DB_PORT: 5432
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
