# Use Node.js LTS as base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./
COPY cities.csv ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Create directory structure for static files
RUN mkdir -p ./public

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application 
CMD ["npm", "start"]
